# Generated by Django 4.0.2 on 2022-02-10 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кинотеатра')),
                ('information', models.TextField(blank=True, default='Информация', null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Кинотеатр',
                'verbose_name_plural': 'Кинотеатры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('age_limit', models.IntegerField(choices=[(0, '0+'), (1, '6+'), (2, '12+'), (3, '16+'), (4, '18+')], verbose_name='Ввозрастное ограничение')),
                ('country', models.CharField(max_length=200, verbose_name='Страна')),
                ('ganres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Жанры')),
                ('director', models.CharField(blank=True, max_length=200, null=True, verbose_name='Режисер')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='images/movies/%y/%m', verbose_name='Постер')),
                ('memorandum', models.DateField(blank=True, null=True, verbose_name='Меморандум')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='С даты')),
                ('premier', models.BooleanField(default=False, verbose_name='ПРемьера')),
                ('carousel', models.ImageField(blank=True, null=True, upload_to='images/carousel/%y/%m', verbose_name='Изображние для карусели')),
                ('trailer', models.FileField(blank=True, null=True, upload_to='', verbose_name='Трейлер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('1', '2D'), ('2', '3D'), ('3', 'IMAX')], max_length=10, verbose_name='Формат')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cinema', verbose_name='Кинотеатр')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
                ('slug', models.SlugField(max_length=100, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('movies', models.ManyToManyField(to='main.Movie', verbose_name='Фильмы')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Город'),
        ),
    ]
