# Generated by Django 4.0.2 on 2022-02-19 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_city_name_alter_city_slug_alter_movie_premier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.movie', verbose_name='Фильм'),
        ),
    ]
