# Generated by Django 4.0.2 on 2022-02-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_session_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, to='main.Movie', verbose_name='Фильмы'),
        ),
    ]
